---
abstract: 'Auditing for tables managed by DBIx::Class'
author:
  - 'Jess Robinson <castaway@desert-island.me.uk>'
build_requires:
  DBD::SQLite: 1.29
  ExtUtils::MakeMaker: 6.42
  SQL::Translator: 0.11003
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Journal
no_index:
  directory:
    - inc
    - t
requires:
  Class::C3::Componentised: 1.0006
  DBIx::Class: 0.08115
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/bast/DBIx-Class-Journal/
version: 0.900102
